# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "pipette_tcp_probe"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
pal_async.workspace = true
pipette_client.workspace = true

[lints]
workspace = true
