# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "disk_backend"
edition.workspace = true
rust-version.workspace = true

[dependencies]
scsi_buffers.workspace = true
vmcore.workspace = true

guestmem.workspace = true
vm_resource.workspace = true
inspect = { workspace = true, features = ["std"] }

async-trait.workspace = true
futures.workspace = true
stackfuture.workspace = true
thiserror.workspace = true

[dev-dependencies]
mesh.workspace = true
pal_async.workspace = true
parking_lot.workspace = true
test_with_tracing.workspace = true

[lints]
workspace = true
