[package]
name = "tmk_launch"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
hvdef.workspace = true

uefi = "0.34.1"
uefi-raw = "0.10.0"

[lints]
workspace = true
