# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Opt-in licensed FVP profile. The runtime publishes requested capabilities
# only after platform validation, boot, and a pipette handshake.
[incubator]
type = "fvp-cca"
consoles = ["host", "edk2", "rmm"]
primary-console = "host"
capabilities = ["cca"]
